name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: ${{ matrix.os }} (${{ matrix.build_type }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug, Release]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@v1.1
        with:
          version: 1.11.1

      - name: Configure CMake
        run: >
          cmake -B build
          -G Ninja
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DENABLE_TESTING=ON
          -DENABLE_INSTALL=ON

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}

      - name: Run Tests
        run: ctest --test-dir build -C ${{ matrix.build_type }} --output-on-failure
